# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13e976f6f0e50249c57baf2a9891385b32ea67b562ea41028f12618301d2912aae23e4f0ff874ae36e8d6fab73e79824414e48b68c2110de0130bd2fa24889ec

test:
  secret_key_base: fa7506c24e934c217904ed600c860d18e55065dfb5d0a73513dcff1dddcf6faac806582161365c840421fc11b7653de2d5fae51b9670208f2617d052f9f77de4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
